version: 2.1
orbs:
  python: circleci/python@1.4.0

workflows:
  sample:
    jobs:
      - build-and-test
      - build
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: python -m pytest
  build:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm ci --prefix ./vue-testfriend
      - run:
          name: Run Tests
          command: npm test
